import numpy

a=numpy.array([],dtype=int)
print(a)
print(a.dtype)
b=numpy.array([1,2,3,4,5,6,7,8,9,10],dtype=int)
c=a.dot(b[3:3])
print(type(c))
print(c)
g=numpy.ones(1,dtype=int)
print(type(g[4]))
print(g)
h=numpy.trim_zeros(g, trim='f')
print(h)
f=numpy.trim_zeros(h, trim='b')
print(f)
i=numpy.trim_zeros(g, trim='fb')
print(i)
j=numpy.pad(i,(3,4),'constant')
print(len(j))
print(j.dtype)